# Generated by Django 5.0.4 on 2024-04-14 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_rename_product_order_id_productcart_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_order_id',
            new_name='product_cart_id',
        ),
    ]
